version: 2

jobs:
  test:
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-cache-v1-{{ .Branch }}-{{ checksum "composer.lock" }}
            - composer-cache-v1-{{ .Branch }}-
            - composer-cache-v1-
      - run: sudo docker-php-ext-install bcmath && sudo docker-php-ext-enable bcmath
      - run: make install_dependencies
      - run: make test
      - save_cache:
          paths:
            - ~/project/vendor
          key: composer-cache-v1-{{ .Branch }}-{{ checksum "composer.lock" }}

workflows:
  version: 2
  test:
    jobs:
      - test
