<?php
namespace CroutonThrift;

/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Protocol\TBinaryProtocolAccelerated;
use Thrift\Exception\TApplicationException;


class KeyValue {
  static $_TSPEC;

  /**
   * @var string
   */
  public $Key = null;
  /**
   * @var string
   */
  public $Value = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'Key',
          'type' => TType::STRING,
          ),
        2 => array(
          'var' => 'Value',
          'type' => TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['Key'])) {
        $this->Key = $vals['Key'];
      }
      if (isset($vals['Value'])) {
        $this->Value = $vals['Value'];
      }
    }
  }

  public function getName() {
    return 'KeyValue';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->Key);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->Value);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('KeyValue');
    if ($this->Key !== null) {
      $xfer += $output->writeFieldBegin('Key', TType::STRING, 1);
      $xfer += $output->writeString($this->Key);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->Value !== null) {
      $xfer += $output->writeFieldBegin('Value', TType::STRING, 2);
      $xfer += $output->writeString($this->Value);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class NamedCounter {
  static $_TSPEC;

  /**
   * @var string
   */
  public $Name = null;
  /**
   * @var int
   */
  public $Value = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'Name',
          'type' => TType::STRING,
          ),
        2 => array(
          'var' => 'Value',
          'type' => TType::I64,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['Name'])) {
        $this->Name = $vals['Name'];
      }
      if (isset($vals['Value'])) {
        $this->Value = $vals['Value'];
      }
    }
  }

  public function getName() {
    return 'NamedCounter';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->Name);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::I64) {
            $xfer += $input->readI64($this->Value);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('NamedCounter');
    if ($this->Name !== null) {
      $xfer += $output->writeFieldBegin('Name', TType::STRING, 1);
      $xfer += $output->writeString($this->Name);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->Value !== null) {
      $xfer += $output->writeFieldBegin('Value', TType::I64, 2);
      $xfer += $output->writeI64($this->Value);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class Runtime {
  static $_TSPEC;

  /**
   * @var string
   */
  public $guid = null;
  /**
   * @var int
   */
  public $start_micros = null;
  /**
   * @var string
   */
  public $group_name = null;
  /**
   * @var \CroutonThrift\KeyValue[]
   */
  public $attrs = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'guid',
          'type' => TType::STRING,
          ),
        2 => array(
          'var' => 'start_micros',
          'type' => TType::I64,
          ),
        3 => array(
          'var' => 'group_name',
          'type' => TType::STRING,
          ),
        4 => array(
          'var' => 'attrs',
          'type' => TType::LST,
          'etype' => TType::STRUCT,
          'elem' => array(
            'type' => TType::STRUCT,
            'class' => '\CroutonThrift\KeyValue',
            ),
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['guid'])) {
        $this->guid = $vals['guid'];
      }
      if (isset($vals['start_micros'])) {
        $this->start_micros = $vals['start_micros'];
      }
      if (isset($vals['group_name'])) {
        $this->group_name = $vals['group_name'];
      }
      if (isset($vals['attrs'])) {
        $this->attrs = $vals['attrs'];
      }
    }
  }

  public function getName() {
    return 'Runtime';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->guid);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::I64) {
            $xfer += $input->readI64($this->start_micros);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 3:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->group_name);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 4:
          if ($ftype == TType::LST) {
            $this->attrs = array();
            $_size0 = 0;
            $_etype3 = 0;
            $xfer += $input->readListBegin($_etype3, $_size0);
            for ($_i4 = 0; $_i4 < $_size0; ++$_i4)
            {
              $elem5 = null;
              $elem5 = new \CroutonThrift\KeyValue();
              $xfer += $elem5->read($input);
              $this->attrs []= $elem5;
            }
            $xfer += $input->readListEnd();
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('Runtime');
    if ($this->guid !== null) {
      $xfer += $output->writeFieldBegin('guid', TType::STRING, 1);
      $xfer += $output->writeString($this->guid);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->start_micros !== null) {
      $xfer += $output->writeFieldBegin('start_micros', TType::I64, 2);
      $xfer += $output->writeI64($this->start_micros);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->group_name !== null) {
      $xfer += $output->writeFieldBegin('group_name', TType::STRING, 3);
      $xfer += $output->writeString($this->group_name);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->attrs !== null) {
      if (!is_array($this->attrs)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('attrs', TType::LST, 4);
      {
        $output->writeListBegin(TType::STRUCT, count($this->attrs));
        {
          foreach ($this->attrs as $iter6)
          {
            $xfer += $iter6->write($output);
          }
        }
        $output->writeListEnd();
      }
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class LogRecord {
  static $_TSPEC;

  /**
   * @var int
   */
  public $timestamp_micros = null;
  /**
   * @var string
   */
  public $runtime_guid = null;
  /**
   * @var string
   */
  public $span_guid = null;
  /**
   * @var string
   */
  public $stable_name = null;
  /**
   * @var string
   */
  public $message = null;
  /**
   * @var string
   */
  public $level = null;
  /**
   * @var int
   */
  public $thread_id = null;
  /**
   * @var string
   */
  public $filename = null;
  /**
   * @var int
   */
  public $line_number = null;
  /**
   * @var string[]
   */
  public $stack_frames = null;
  /**
   * @var string
   */
  public $payload_json = null;
  /**
   * @var bool
   */
  public $error_flag = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'timestamp_micros',
          'type' => TType::I64,
          ),
        2 => array(
          'var' => 'runtime_guid',
          'type' => TType::STRING,
          ),
        3 => array(
          'var' => 'span_guid',
          'type' => TType::STRING,
          ),
        4 => array(
          'var' => 'stable_name',
          'type' => TType::STRING,
          ),
        5 => array(
          'var' => 'message',
          'type' => TType::STRING,
          ),
        6 => array(
          'var' => 'level',
          'type' => TType::STRING,
          ),
        7 => array(
          'var' => 'thread_id',
          'type' => TType::I64,
          ),
        8 => array(
          'var' => 'filename',
          'type' => TType::STRING,
          ),
        9 => array(
          'var' => 'line_number',
          'type' => TType::I64,
          ),
        10 => array(
          'var' => 'stack_frames',
          'type' => TType::LST,
          'etype' => TType::STRING,
          'elem' => array(
            'type' => TType::STRING,
            ),
          ),
        11 => array(
          'var' => 'payload_json',
          'type' => TType::STRING,
          ),
        12 => array(
          'var' => 'error_flag',
          'type' => TType::BOOL,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['timestamp_micros'])) {
        $this->timestamp_micros = $vals['timestamp_micros'];
      }
      if (isset($vals['runtime_guid'])) {
        $this->runtime_guid = $vals['runtime_guid'];
      }
      if (isset($vals['span_guid'])) {
        $this->span_guid = $vals['span_guid'];
      }
      if (isset($vals['stable_name'])) {
        $this->stable_name = $vals['stable_name'];
      }
      if (isset($vals['message'])) {
        $this->message = $vals['message'];
      }
      if (isset($vals['level'])) {
        $this->level = $vals['level'];
      }
      if (isset($vals['thread_id'])) {
        $this->thread_id = $vals['thread_id'];
      }
      if (isset($vals['filename'])) {
        $this->filename = $vals['filename'];
      }
      if (isset($vals['line_number'])) {
        $this->line_number = $vals['line_number'];
      }
      if (isset($vals['stack_frames'])) {
        $this->stack_frames = $vals['stack_frames'];
      }
      if (isset($vals['payload_json'])) {
        $this->payload_json = $vals['payload_json'];
      }
      if (isset($vals['error_flag'])) {
        $this->error_flag = $vals['error_flag'];
      }
    }
  }

  public function getName() {
    return 'LogRecord';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::I64) {
            $xfer += $input->readI64($this->timestamp_micros);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->runtime_guid);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 3:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->span_guid);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 4:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->stable_name);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 5:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->message);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 6:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->level);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 7:
          if ($ftype == TType::I64) {
            $xfer += $input->readI64($this->thread_id);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 8:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->filename);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 9:
          if ($ftype == TType::I64) {
            $xfer += $input->readI64($this->line_number);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 10:
          if ($ftype == TType::LST) {
            $this->stack_frames = array();
            $_size7 = 0;
            $_etype10 = 0;
            $xfer += $input->readListBegin($_etype10, $_size7);
            for ($_i11 = 0; $_i11 < $_size7; ++$_i11)
            {
              $elem12 = null;
              $xfer += $input->readString($elem12);
              $this->stack_frames []= $elem12;
            }
            $xfer += $input->readListEnd();
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 11:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->payload_json);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 12:
          if ($ftype == TType::BOOL) {
            $xfer += $input->readBool($this->error_flag);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('LogRecord');
    if ($this->timestamp_micros !== null) {
      $xfer += $output->writeFieldBegin('timestamp_micros', TType::I64, 1);
      $xfer += $output->writeI64($this->timestamp_micros);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->runtime_guid !== null) {
      $xfer += $output->writeFieldBegin('runtime_guid', TType::STRING, 2);
      $xfer += $output->writeString($this->runtime_guid);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->span_guid !== null) {
      $xfer += $output->writeFieldBegin('span_guid', TType::STRING, 3);
      $xfer += $output->writeString($this->span_guid);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->stable_name !== null) {
      $xfer += $output->writeFieldBegin('stable_name', TType::STRING, 4);
      $xfer += $output->writeString($this->stable_name);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->message !== null) {
      $xfer += $output->writeFieldBegin('message', TType::STRING, 5);
      $xfer += $output->writeString($this->message);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->level !== null) {
      $xfer += $output->writeFieldBegin('level', TType::STRING, 6);
      $xfer += $output->writeString($this->level);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->thread_id !== null) {
      $xfer += $output->writeFieldBegin('thread_id', TType::I64, 7);
      $xfer += $output->writeI64($this->thread_id);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->filename !== null) {
      $xfer += $output->writeFieldBegin('filename', TType::STRING, 8);
      $xfer += $output->writeString($this->filename);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->line_number !== null) {
      $xfer += $output->writeFieldBegin('line_number', TType::I64, 9);
      $xfer += $output->writeI64($this->line_number);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->stack_frames !== null) {
      if (!is_array($this->stack_frames)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('stack_frames', TType::LST, 10);
      {
        $output->writeListBegin(TType::STRING, count($this->stack_frames));
        {
          foreach ($this->stack_frames as $iter13)
          {
            $xfer += $output->writeString($iter13);
          }
        }
        $output->writeListEnd();
      }
      $xfer += $output->writeFieldEnd();
    }
    if ($this->payload_json !== null) {
      $xfer += $output->writeFieldBegin('payload_json', TType::STRING, 11);
      $xfer += $output->writeString($this->payload_json);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->error_flag !== null) {
      $xfer += $output->writeFieldBegin('error_flag', TType::BOOL, 12);
      $xfer += $output->writeBool($this->error_flag);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class TraceJoinId {
  static $_TSPEC;

  /**
   * @var string
   */
  public $TraceKey = null;
  /**
   * @var string
   */
  public $Value = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'TraceKey',
          'type' => TType::STRING,
          ),
        2 => array(
          'var' => 'Value',
          'type' => TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['TraceKey'])) {
        $this->TraceKey = $vals['TraceKey'];
      }
      if (isset($vals['Value'])) {
        $this->Value = $vals['Value'];
      }
    }
  }

  public function getName() {
    return 'TraceJoinId';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->TraceKey);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->Value);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('TraceJoinId');
    if ($this->TraceKey !== null) {
      $xfer += $output->writeFieldBegin('TraceKey', TType::STRING, 1);
      $xfer += $output->writeString($this->TraceKey);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->Value !== null) {
      $xfer += $output->writeFieldBegin('Value', TType::STRING, 2);
      $xfer += $output->writeString($this->Value);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class SpanRecord {
  static $_TSPEC;

  /**
   * @var string
   */
  public $span_guid = null;
  /**
   * @var string
   */
  public $runtime_guid = null;
  /**
   * @var string
   */
  public $span_name = null;
  /**
   * @var \CroutonThrift\TraceJoinId[]
   */
  public $join_ids = null;
  /**
   * @var int
   */
  public $oldest_micros = null;
  /**
   * @var int
   */
  public $youngest_micros = null;
  /**
   * @var \CroutonThrift\KeyValue[]
   */
  public $attributes = null;
  /**
   * @var bool
   */
  public $error_flag = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'span_guid',
          'type' => TType::STRING,
          ),
        2 => array(
          'var' => 'runtime_guid',
          'type' => TType::STRING,
          ),
        3 => array(
          'var' => 'span_name',
          'type' => TType::STRING,
          ),
        4 => array(
          'var' => 'join_ids',
          'type' => TType::LST,
          'etype' => TType::STRUCT,
          'elem' => array(
            'type' => TType::STRUCT,
            'class' => '\CroutonThrift\TraceJoinId',
            ),
          ),
        5 => array(
          'var' => 'oldest_micros',
          'type' => TType::I64,
          ),
        6 => array(
          'var' => 'youngest_micros',
          'type' => TType::I64,
          ),
        8 => array(
          'var' => 'attributes',
          'type' => TType::LST,
          'etype' => TType::STRUCT,
          'elem' => array(
            'type' => TType::STRUCT,
            'class' => '\CroutonThrift\KeyValue',
            ),
          ),
        9 => array(
          'var' => 'error_flag',
          'type' => TType::BOOL,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['span_guid'])) {
        $this->span_guid = $vals['span_guid'];
      }
      if (isset($vals['runtime_guid'])) {
        $this->runtime_guid = $vals['runtime_guid'];
      }
      if (isset($vals['span_name'])) {
        $this->span_name = $vals['span_name'];
      }
      if (isset($vals['join_ids'])) {
        $this->join_ids = $vals['join_ids'];
      }
      if (isset($vals['oldest_micros'])) {
        $this->oldest_micros = $vals['oldest_micros'];
      }
      if (isset($vals['youngest_micros'])) {
        $this->youngest_micros = $vals['youngest_micros'];
      }
      if (isset($vals['attributes'])) {
        $this->attributes = $vals['attributes'];
      }
      if (isset($vals['error_flag'])) {
        $this->error_flag = $vals['error_flag'];
      }
    }
  }

  public function getName() {
    return 'SpanRecord';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->span_guid);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->runtime_guid);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 3:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->span_name);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 4:
          if ($ftype == TType::LST) {
            $this->join_ids = array();
            $_size14 = 0;
            $_etype17 = 0;
            $xfer += $input->readListBegin($_etype17, $_size14);
            for ($_i18 = 0; $_i18 < $_size14; ++$_i18)
            {
              $elem19 = null;
              $elem19 = new \CroutonThrift\TraceJoinId();
              $xfer += $elem19->read($input);
              $this->join_ids []= $elem19;
            }
            $xfer += $input->readListEnd();
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 5:
          if ($ftype == TType::I64) {
            $xfer += $input->readI64($this->oldest_micros);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 6:
          if ($ftype == TType::I64) {
            $xfer += $input->readI64($this->youngest_micros);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 8:
          if ($ftype == TType::LST) {
            $this->attributes = array();
            $_size20 = 0;
            $_etype23 = 0;
            $xfer += $input->readListBegin($_etype23, $_size20);
            for ($_i24 = 0; $_i24 < $_size20; ++$_i24)
            {
              $elem25 = null;
              $elem25 = new \CroutonThrift\KeyValue();
              $xfer += $elem25->read($input);
              $this->attributes []= $elem25;
            }
            $xfer += $input->readListEnd();
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 9:
          if ($ftype == TType::BOOL) {
            $xfer += $input->readBool($this->error_flag);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('SpanRecord');
    if ($this->span_guid !== null) {
      $xfer += $output->writeFieldBegin('span_guid', TType::STRING, 1);
      $xfer += $output->writeString($this->span_guid);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->runtime_guid !== null) {
      $xfer += $output->writeFieldBegin('runtime_guid', TType::STRING, 2);
      $xfer += $output->writeString($this->runtime_guid);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->span_name !== null) {
      $xfer += $output->writeFieldBegin('span_name', TType::STRING, 3);
      $xfer += $output->writeString($this->span_name);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->join_ids !== null) {
      if (!is_array($this->join_ids)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('join_ids', TType::LST, 4);
      {
        $output->writeListBegin(TType::STRUCT, count($this->join_ids));
        {
          foreach ($this->join_ids as $iter26)
          {
            $xfer += $iter26->write($output);
          }
        }
        $output->writeListEnd();
      }
      $xfer += $output->writeFieldEnd();
    }
    if ($this->oldest_micros !== null) {
      $xfer += $output->writeFieldBegin('oldest_micros', TType::I64, 5);
      $xfer += $output->writeI64($this->oldest_micros);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->youngest_micros !== null) {
      $xfer += $output->writeFieldBegin('youngest_micros', TType::I64, 6);
      $xfer += $output->writeI64($this->youngest_micros);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->attributes !== null) {
      if (!is_array($this->attributes)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('attributes', TType::LST, 8);
      {
        $output->writeListBegin(TType::STRUCT, count($this->attributes));
        {
          foreach ($this->attributes as $iter27)
          {
            $xfer += $iter27->write($output);
          }
        }
        $output->writeListEnd();
      }
      $xfer += $output->writeFieldEnd();
    }
    if ($this->error_flag !== null) {
      $xfer += $output->writeFieldBegin('error_flag', TType::BOOL, 9);
      $xfer += $output->writeBool($this->error_flag);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class Auth {
  static $_TSPEC;

  /**
   * @var string
   */
  public $access_token = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'access_token',
          'type' => TType::STRING,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['access_token'])) {
        $this->access_token = $vals['access_token'];
      }
    }
  }

  public function getName() {
    return 'Auth';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRING) {
            $xfer += $input->readString($this->access_token);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('Auth');
    if ($this->access_token !== null) {
      $xfer += $output->writeFieldBegin('access_token', TType::STRING, 1);
      $xfer += $output->writeString($this->access_token);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class Timing {
  static $_TSPEC;

  /**
   * @var int
   */
  public $receive_micros = null;
  /**
   * @var int
   */
  public $transmit_micros = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'receive_micros',
          'type' => TType::I64,
          ),
        2 => array(
          'var' => 'transmit_micros',
          'type' => TType::I64,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['receive_micros'])) {
        $this->receive_micros = $vals['receive_micros'];
      }
      if (isset($vals['transmit_micros'])) {
        $this->transmit_micros = $vals['transmit_micros'];
      }
    }
  }

  public function getName() {
    return 'Timing';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::I64) {
            $xfer += $input->readI64($this->receive_micros);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::I64) {
            $xfer += $input->readI64($this->transmit_micros);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('Timing');
    if ($this->receive_micros !== null) {
      $xfer += $output->writeFieldBegin('receive_micros', TType::I64, 1);
      $xfer += $output->writeI64($this->receive_micros);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->transmit_micros !== null) {
      $xfer += $output->writeFieldBegin('transmit_micros', TType::I64, 2);
      $xfer += $output->writeI64($this->transmit_micros);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class SampleCount {
  static $_TSPEC;

  /**
   * @var int
   */
  public $oldest_micros = null;
  /**
   * @var int
   */
  public $youngest_micros = null;
  /**
   * @var int
   */
  public $count = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'oldest_micros',
          'type' => TType::I64,
          ),
        2 => array(
          'var' => 'youngest_micros',
          'type' => TType::I64,
          ),
        3 => array(
          'var' => 'count',
          'type' => TType::I64,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['oldest_micros'])) {
        $this->oldest_micros = $vals['oldest_micros'];
      }
      if (isset($vals['youngest_micros'])) {
        $this->youngest_micros = $vals['youngest_micros'];
      }
      if (isset($vals['count'])) {
        $this->count = $vals['count'];
      }
    }
  }

  public function getName() {
    return 'SampleCount';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::I64) {
            $xfer += $input->readI64($this->oldest_micros);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::I64) {
            $xfer += $input->readI64($this->youngest_micros);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 3:
          if ($ftype == TType::I64) {
            $xfer += $input->readI64($this->count);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('SampleCount');
    if ($this->oldest_micros !== null) {
      $xfer += $output->writeFieldBegin('oldest_micros', TType::I64, 1);
      $xfer += $output->writeI64($this->oldest_micros);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->youngest_micros !== null) {
      $xfer += $output->writeFieldBegin('youngest_micros', TType::I64, 2);
      $xfer += $output->writeI64($this->youngest_micros);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->count !== null) {
      $xfer += $output->writeFieldBegin('count', TType::I64, 3);
      $xfer += $output->writeI64($this->count);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class ReportRequest {
  static $_TSPEC;

  /**
   * @var \CroutonThrift\Runtime
   */
  public $runtime = null;
  /**
   * @var \CroutonThrift\SpanRecord[]
   */
  public $span_records = null;
  /**
   * @var \CroutonThrift\LogRecord[]
   */
  public $log_records = null;
  /**
   * @var int
   */
  public $timestamp_offset_micros = null;
  /**
   * @var int
   */
  public $oldest_micros = null;
  /**
   * @var int
   */
  public $youngest_micros = null;
  /**
   * @var \CroutonThrift\NamedCounter[]
   */
  public $counters = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'runtime',
          'type' => TType::STRUCT,
          'class' => '\CroutonThrift\Runtime',
          ),
        3 => array(
          'var' => 'span_records',
          'type' => TType::LST,
          'etype' => TType::STRUCT,
          'elem' => array(
            'type' => TType::STRUCT,
            'class' => '\CroutonThrift\SpanRecord',
            ),
          ),
        4 => array(
          'var' => 'log_records',
          'type' => TType::LST,
          'etype' => TType::STRUCT,
          'elem' => array(
            'type' => TType::STRUCT,
            'class' => '\CroutonThrift\LogRecord',
            ),
          ),
        5 => array(
          'var' => 'timestamp_offset_micros',
          'type' => TType::I64,
          ),
        7 => array(
          'var' => 'oldest_micros',
          'type' => TType::I64,
          ),
        8 => array(
          'var' => 'youngest_micros',
          'type' => TType::I64,
          ),
        9 => array(
          'var' => 'counters',
          'type' => TType::LST,
          'etype' => TType::STRUCT,
          'elem' => array(
            'type' => TType::STRUCT,
            'class' => '\CroutonThrift\NamedCounter',
            ),
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['runtime'])) {
        $this->runtime = $vals['runtime'];
      }
      if (isset($vals['span_records'])) {
        $this->span_records = $vals['span_records'];
      }
      if (isset($vals['log_records'])) {
        $this->log_records = $vals['log_records'];
      }
      if (isset($vals['timestamp_offset_micros'])) {
        $this->timestamp_offset_micros = $vals['timestamp_offset_micros'];
      }
      if (isset($vals['oldest_micros'])) {
        $this->oldest_micros = $vals['oldest_micros'];
      }
      if (isset($vals['youngest_micros'])) {
        $this->youngest_micros = $vals['youngest_micros'];
      }
      if (isset($vals['counters'])) {
        $this->counters = $vals['counters'];
      }
    }
  }

  public function getName() {
    return 'ReportRequest';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::STRUCT) {
            $this->runtime = new \CroutonThrift\Runtime();
            $xfer += $this->runtime->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 3:
          if ($ftype == TType::LST) {
            $this->span_records = array();
            $_size28 = 0;
            $_etype31 = 0;
            $xfer += $input->readListBegin($_etype31, $_size28);
            for ($_i32 = 0; $_i32 < $_size28; ++$_i32)
            {
              $elem33 = null;
              $elem33 = new \CroutonThrift\SpanRecord();
              $xfer += $elem33->read($input);
              $this->span_records []= $elem33;
            }
            $xfer += $input->readListEnd();
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 4:
          if ($ftype == TType::LST) {
            $this->log_records = array();
            $_size34 = 0;
            $_etype37 = 0;
            $xfer += $input->readListBegin($_etype37, $_size34);
            for ($_i38 = 0; $_i38 < $_size34; ++$_i38)
            {
              $elem39 = null;
              $elem39 = new \CroutonThrift\LogRecord();
              $xfer += $elem39->read($input);
              $this->log_records []= $elem39;
            }
            $xfer += $input->readListEnd();
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 5:
          if ($ftype == TType::I64) {
            $xfer += $input->readI64($this->timestamp_offset_micros);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 7:
          if ($ftype == TType::I64) {
            $xfer += $input->readI64($this->oldest_micros);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 8:
          if ($ftype == TType::I64) {
            $xfer += $input->readI64($this->youngest_micros);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 9:
          if ($ftype == TType::LST) {
            $this->counters = array();
            $_size40 = 0;
            $_etype43 = 0;
            $xfer += $input->readListBegin($_etype43, $_size40);
            for ($_i44 = 0; $_i44 < $_size40; ++$_i44)
            {
              $elem45 = null;
              $elem45 = new \CroutonThrift\NamedCounter();
              $xfer += $elem45->read($input);
              $this->counters []= $elem45;
            }
            $xfer += $input->readListEnd();
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('ReportRequest');
    if ($this->runtime !== null) {
      if (!is_object($this->runtime)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('runtime', TType::STRUCT, 1);
      $xfer += $this->runtime->write($output);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->span_records !== null) {
      if (!is_array($this->span_records)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('span_records', TType::LST, 3);
      {
        $output->writeListBegin(TType::STRUCT, count($this->span_records));
        {
          foreach ($this->span_records as $iter46)
          {
            $xfer += $iter46->write($output);
          }
        }
        $output->writeListEnd();
      }
      $xfer += $output->writeFieldEnd();
    }
    if ($this->log_records !== null) {
      if (!is_array($this->log_records)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('log_records', TType::LST, 4);
      {
        $output->writeListBegin(TType::STRUCT, count($this->log_records));
        {
          foreach ($this->log_records as $iter47)
          {
            $xfer += $iter47->write($output);
          }
        }
        $output->writeListEnd();
      }
      $xfer += $output->writeFieldEnd();
    }
    if ($this->timestamp_offset_micros !== null) {
      $xfer += $output->writeFieldBegin('timestamp_offset_micros', TType::I64, 5);
      $xfer += $output->writeI64($this->timestamp_offset_micros);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->oldest_micros !== null) {
      $xfer += $output->writeFieldBegin('oldest_micros', TType::I64, 7);
      $xfer += $output->writeI64($this->oldest_micros);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->youngest_micros !== null) {
      $xfer += $output->writeFieldBegin('youngest_micros', TType::I64, 8);
      $xfer += $output->writeI64($this->youngest_micros);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->counters !== null) {
      if (!is_array($this->counters)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('counters', TType::LST, 9);
      {
        $output->writeListBegin(TType::STRUCT, count($this->counters));
        {
          foreach ($this->counters as $iter48)
          {
            $xfer += $iter48->write($output);
          }
        }
        $output->writeListEnd();
      }
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class Command {
  static $_TSPEC;

  /**
   * @var bool
   */
  public $disable = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'disable',
          'type' => TType::BOOL,
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['disable'])) {
        $this->disable = $vals['disable'];
      }
    }
  }

  public function getName() {
    return 'Command';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::BOOL) {
            $xfer += $input->readBool($this->disable);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('Command');
    if ($this->disable !== null) {
      $xfer += $output->writeFieldBegin('disable', TType::BOOL, 1);
      $xfer += $output->writeBool($this->disable);
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}

class ReportResponse {
  static $_TSPEC;

  /**
   * @var \CroutonThrift\Command[]
   */
  public $commands = null;
  /**
   * @var \CroutonThrift\Timing
   */
  public $timing = null;
  /**
   * @var string[]
   */
  public $errors = null;

  public function __construct($vals=null) {
    if (!isset(self::$_TSPEC)) {
      self::$_TSPEC = array(
        1 => array(
          'var' => 'commands',
          'type' => TType::LST,
          'etype' => TType::STRUCT,
          'elem' => array(
            'type' => TType::STRUCT,
            'class' => '\CroutonThrift\Command',
            ),
          ),
        2 => array(
          'var' => 'timing',
          'type' => TType::STRUCT,
          'class' => '\CroutonThrift\Timing',
          ),
        3 => array(
          'var' => 'errors',
          'type' => TType::LST,
          'etype' => TType::STRING,
          'elem' => array(
            'type' => TType::STRING,
            ),
          ),
        );
    }
    if (is_array($vals)) {
      if (isset($vals['commands'])) {
        $this->commands = $vals['commands'];
      }
      if (isset($vals['timing'])) {
        $this->timing = $vals['timing'];
      }
      if (isset($vals['errors'])) {
        $this->errors = $vals['errors'];
      }
    }
  }

  public function getName() {
    return 'ReportResponse';
  }

  public function read($input)
  {
    $xfer = 0;
    $fname = null;
    $ftype = 0;
    $fid = 0;
    $xfer += $input->readStructBegin($fname);
    while (true)
    {
      $xfer += $input->readFieldBegin($fname, $ftype, $fid);
      if ($ftype == TType::STOP) {
        break;
      }
      switch ($fid)
      {
        case 1:
          if ($ftype == TType::LST) {
            $this->commands = array();
            $_size49 = 0;
            $_etype52 = 0;
            $xfer += $input->readListBegin($_etype52, $_size49);
            for ($_i53 = 0; $_i53 < $_size49; ++$_i53)
            {
              $elem54 = null;
              $elem54 = new \CroutonThrift\Command();
              $xfer += $elem54->read($input);
              $this->commands []= $elem54;
            }
            $xfer += $input->readListEnd();
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 2:
          if ($ftype == TType::STRUCT) {
            $this->timing = new \CroutonThrift\Timing();
            $xfer += $this->timing->read($input);
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        case 3:
          if ($ftype == TType::LST) {
            $this->errors = array();
            $_size55 = 0;
            $_etype58 = 0;
            $xfer += $input->readListBegin($_etype58, $_size55);
            for ($_i59 = 0; $_i59 < $_size55; ++$_i59)
            {
              $elem60 = null;
              $xfer += $input->readString($elem60);
              $this->errors []= $elem60;
            }
            $xfer += $input->readListEnd();
          } else {
            $xfer += $input->skip($ftype);
          }
          break;
        default:
          $xfer += $input->skip($ftype);
          break;
      }
      $xfer += $input->readFieldEnd();
    }
    $xfer += $input->readStructEnd();
    return $xfer;
  }

  public function write($output) {
    $xfer = 0;
    $xfer += $output->writeStructBegin('ReportResponse');
    if ($this->commands !== null) {
      if (!is_array($this->commands)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('commands', TType::LST, 1);
      {
        $output->writeListBegin(TType::STRUCT, count($this->commands));
        {
          foreach ($this->commands as $iter61)
          {
            $xfer += $iter61->write($output);
          }
        }
        $output->writeListEnd();
      }
      $xfer += $output->writeFieldEnd();
    }
    if ($this->timing !== null) {
      if (!is_object($this->timing)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('timing', TType::STRUCT, 2);
      $xfer += $this->timing->write($output);
      $xfer += $output->writeFieldEnd();
    }
    if ($this->errors !== null) {
      if (!is_array($this->errors)) {
        throw new TProtocolException('Bad type in structure.', TProtocolException::INVALID_DATA);
      }
      $xfer += $output->writeFieldBegin('errors', TType::LST, 3);
      {
        $output->writeListBegin(TType::STRING, count($this->errors));
        {
          foreach ($this->errors as $iter62)
          {
            $xfer += $output->writeString($iter62);
          }
        }
        $output->writeListEnd();
      }
      $xfer += $output->writeFieldEnd();
    }
    $xfer += $output->writeFieldStop();
    $xfer += $output->writeStructEnd();
    return $xfer;
  }

}


